Refactor: Reset scene containers
kaamaurice/OpenPype pull request #142
Opened 2023-08-03 07:04 UTC by Tilix4

## Changelog Description
This refactors the way container datablocks are collected. As since we don't store containers into `scene`, the list has to be recreated each time we open the `Manage`. This algorithm is faster and more reliable.

## Testing notes:
1. Open any scene (tested on `e102_sh011` among others)
2. Open the manage
3. Try to switch or remove Willy (or any other rig/props/setdress)

2023-08-03 09:34 UTC, Sharkitty requested changes

2023-08-03 09:34 UTC, Sharkitty commented on openpype/hosts/blender/api/lib.py
> +        types = (types,)
Why is there a comma?

2023-08-03 09:34 UTC, Sharkitty commented on openpype/hosts/blender/api/lib.py
> +    """Recursive function to collect all datablocks linked to the user datablock.
Line too long.

2023-08-03 09:40 UTC, Sharkitty commented
```
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/blender_addon/startup/init.py", line 6, in <module>
    from openpype.hosts.blender.api.utils import assign_loader_to_datablocks
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/__init__.py", line 7, in <module>
    from .pipeline import (
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/pipeline.py", line 10, in <module>
    from . import ops, properties, ui
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/ops.py", line 38, in <module>
    from openpype.hosts.blender.scripts import build_workfile
  File "/home/sharkitty/work/normaal/workenv/blender-3.6.1-linux-x64/3.6/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/scripts/__init__.py", line 1, in <module>
    from .build_workfile import build_workfile
  File "/home/sharkitty/work/normaal/workenv/blender-3.6.1-linux-x64/3.6/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/scripts/build_workfile.py", line 21, in <module>
    from openpype.hosts.blender.api.lib import (
ImportError: cannot import name 'update_scene_containers' from 'openpype.hosts.blender.api.lib' (/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/lib.py)
```
This causes an import error for me.

2023-08-03 12:02 UTC, Tilix4 commented
Have you correctly fixed the conflicts by removing all unused references?

2023-08-03 12:08 UTC, Sharkitty commented
> Have you correctly fixed the conflicts by removing all unused references?

I resolved conflicts, but the file producing the error does not have conflicts.

2023-08-03 12:18 UTC, Tilix4 commented
I messed my branches.
Should be fixed now

2023-08-03 12:38 UTC, Sharkitty commented
Works now

2023-08-03 13:41 UTC, Tilix4 commented on openpype/hosts/blender/api/lib.py
> +        types = (types,)
To build a `tuple`, eitherway `(types) == types`

2023-08-03 13:42 UTC, Tilix4 commented on openpype/hosts/blender/api/lib.py
> +    """Recursive function to collect all datablocks linked to the user datablock.
fixed

2023-08-03 14:09 UTC, Sharkitty commented on openpype/hosts/blender/api/lib.py
> +        types = (types,)
Ooooh I see!

2023-08-03 14:09 UTC, Sharkitty approved these changes

2023-08-03 14:15 UTC, Tilix4 commented
As it is a change which could have unexpected side effects and I leave soon for long vacations, I propose to add it to the studio code gathering instead of merging and rebasing the whole branches stack. This way if it introduces issues, you'll basically have to remove it from the branches auto gathering list.

2023-08-03 14:18 UTC, Sharkitty commented
> Because it is a change which could have unexpected side effects and I leave soon for long vacations, I propose to add it to the studio code gathering instead of merging and rebasing the whole branches stack. This way if it introduces issues, you'll basically have to remove it from the branches auto gathering list.

That's a good idea, I'll add this branch to my list.

2023-08-03 14:21 UTC, Tilix4 commented
Pushed a change of `branches.ini` on master

2023-08-04 14:33 UTC, Sharkitty approved these changes
Manage window has a more decent speed that way :smile:

2023-08-11 08:27 UTC, Sharkitty commented
Hello! We encountered some issue, causing the loader to load  infinitely. @kaamaurice investigated and came to the conclusion that a recursive method used in this code was the source of this issue, and that the amount of calls increases exponentially with the amount of objects in the scene. He started working on a fix although he is now in vacation, so I will try to continue his work. No harm made in production, we just rollbacked this refactor.

2023-08-15 15:36 UTC, Sharkitty commented
After investigating on the issue I managed to fix the issue, and opened [a PR containing the fix](https://github.com/Tilix4/OpenPype/pull/61). It was actually simpler than what I expected.

2023-09-04 09:16 UTC, Sharkitty approved these changes
LGTM

2023-09-06 15:42 UTC, merged