Refactor loader clean api
kaamaurice/OpenPype pull request #153
Opened 2023-11-23 09:28 UTC by Tilix4

## Changelog Description
The goal is to define a clean and unified API for the loaders. The main idea is to split pure blender operations, like dealing with the datablocks, and OP operations, like containerization.

Currently it deals only with the Blend files, other formats loaders currently supported by OP (fbx, abc...) will be dealt with in a following PR.

`datapath` has been renamed to `datacol` to be more explicit, as it is about the blender `collection` concept (close to a `list`).

## Testing notes:
1. Regular loading usage.

2023-12-04 11:22 UTC, Sharkitty requested changes

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/ops.py
> +    if self.datacol in {BL_TYPE_DATACOL.get(t) for t in BL_OUTLINER_TYPES} and bpy.types.Collection.__name__ in {
Line too long

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +    Outliner types (Collections and Objects) may have some treatment exceptions.
Line too long

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        raise NotImplementedError()
Uhm, I guess it's just borked then, since this is called in the `load` method.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        container, datablocks = self._load_library_as_container(libpath, container_basename)
Line too long and call of this method as is will just raise an error.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        the name the datablock has in the source blend file is kept as 'source_name'.
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        container, datablocks = self._load_library_as_container(
Call to method without implementation.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +            if isinstance(obj, bpy.types.Object) and getattr(obj.override_library, "operations_update", None):
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        As Blender purges datablocks is not used,clearing all
```suggestion
        As Blender datablocks purge is not used, clearing all
```

```suggestion
        As datablocks are not purged in Blender, clearing all
```

Seems oddly worded, and a missing space after `,`.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        datablocks = load_blend_datablocks(libpath, self.bl_types, link, do_override)
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/utils.py
> +def replace_datablocks(old_datablocks:Set[bpy.types.ID], new_datablocks:Set[bpy.types.ID]):
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/utils.py
> +    for outliner_datablock in get_root_datablocks(old_datablocks, BL_OUTLINER_TYPES):
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/api/utils.py
> +                                old_datablock.data.shape_keys.animation_data.drivers[
Line too long.

2023-12-04 11:22 UTC, Sharkitty commented on openpype/hosts/blender/utility_scripts/update_representations.py
> +        help="list of data collections (bpy.data.<collection>) to get datablocks from",
Line too long.

2023-12-05 06:23 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        raise NotImplementedError()
I don't get your point, this is actually the goal of an `abstractmethod`, to be implemented in inheriting classes, and this function is supposed to be the only required one to be implemented.

2023-12-05 06:36 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        container, datablocks = self._load_library_as_container(
Same, abstract class, on purpose.

2023-12-05 14:29 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        raise NotImplementedError()
Right, I missed that part. But none of the plugins that implement `Loader` directly, instead of `BlendLoader` don't implement this method. Which is called in `load`. So they should error out.

2023-12-05 14:34 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        raise NotImplementedError()
That is exactly the point of the penultimate paragraph of the PR description :smile:

2023-12-05 14:35 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +        raise NotImplementedError()
Oh right... Sorry x)

2023-12-06 10:37 UTC, Tilix4 commented on openpype/hosts/blender/api/utils.py
> +                                old_datablock.data.shape_keys.animation_data.drivers[
Yes but that's how black formats it

2023-12-06 13:50 UTC, Sharkitty commented on openpype/hosts/blender/api/utils.py
> +                                old_datablock.data.shape_keys.animation_data.drivers[
```suggestion
                                old_datablock
                                .data
                                .shape_keys
                                .animation_data
                                .drivers[
```
If this is meant to be merged upstream, they'll check for linting and this won't pass.

2023-12-06 16:44 UTC, Sharkitty commented
```
During load error happened on Subset: "setdressMain" Representation: "blend" Version: 5

Error message: getattr(): attribute name must be string

Traceback (most recent call last):
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/tools/loader/widgets.py", line 1590, in _load_representations_by_loader
    load_with_repre_context(
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/pipeline/load/utils.py", line 308, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/plugin.py", line 276, in wrapper_exec_process
    return process_func(*args, **kwargs)
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/plugin.py", line 648, in load
    container, datablocks = self.load_library_as_container(
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/plugin.py", line 1111, in load_library_as_container
    return load_func(*args, **kwargs)
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/plugin.py", line 974, in _link_blend
    container, all_datablocks = self._load_blend_datablocks_as_container(
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/plugin.py", line 930, in _load_blend_datablocks_as_container
    datablocks = load_blend_datablocks(
  File "/home/sharkitty/work/normaal/repos/openpype-for-normaal/openpype/hosts/blender/api/utils.py", line 611, in load_blend_datablocks
    loaded_datablocks = list(getattr(data_from, data_collection_name))
TypeError: getattr(): attribute name must be string
```

Failed to load AuntieCuisine_004_B_JOUR setdress v005.

2023-12-08 14:13 UTC, Tilix4 commented
@Sharkitty This bug is because your setdress loader is overriden and tries to load the `World` type. Either you disconnect your normaal addon or comment the `bl_type` frow the `LinkWoollySetdressLoader`

2023-12-08 14:24 UTC, Sharkitty commented
> @Sharkitty This bug is because your setdress loader is overriden and tries to load the `World` type. Either you disconnect your normaal addon or comment the `bl_type` frow the `LinkWoollySetdressLoader`

It's as I suspected. Then the issue I encountered is not related to this PR. All other tests passed for me.

2023-12-08 14:24 UTC, Sharkitty approved these changes

2023-12-08 17:00 UTC, merged