Fix: Switch transfer custom properties
kaamaurice/OpenPype pull request #156
Opened 2023-12-06 10:29 UTC by Tilix4

Ensure custom properties are correctly transferred, at least for main datablocks and bones.

## Testing notes:
1. Cherry-pick upon last normaal staging release.
1. Open `e108_sh001` anim
2. Toggle pose mode for `Room_Billes01`
3. Go to bone `walk`, and modify `roll_simulation_pause_frames` string value with the word you like.
4. In manage, update `Room_Billes01` to latest
5. Toggle pose mode again for `Room_Billes01` and check `roll_simulation_pause_frames` value

2023-12-06 14:15 UTC, Sharkitty requested changes

2023-12-06 14:15 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +                                    new_source_bone = new_datablock.override_library.reference.pose.bones[
Linting.

2023-12-06 15:13 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +                                    new_source_bone = new_datablock.override_library.reference.pose.bones[
that's what black does

2023-12-06 16:34 UTC, Sharkitty commented on openpype/hosts/blender/api/plugin.py
> +                                    new_source_bone = new_datablock.override_library.reference.pose.bones[
Black doesn't format comments, and again, that won't pass upstream.

2023-12-07 13:45 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +                                    new_source_bone = new_datablock.override_library.reference.pose.bones[
Yes okay for the comments, but about the `.` chaining I'm surprised it is left like this

2023-12-07 15:55 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +                                    new_source_bone = new_datablock.override_library.reference.pose.bones[
changed

2023-12-08 13:53 UTC, Sharkitty approved these changes

2023-12-08 13:58 UTC, merged