Fix seamless with no namespace and no maintainer
kaamaurice/OpenPype pull request #43
Opened 2023-01-19 09:45 UTC by kaamaurice

## Description
- fixed some hound bot reviews blank `line contains whitespace` and `line too long ( > 79 characters)`
- removed namespace (the namespaces could appear in the nomenclature after an update or a switch)
- remove context maintainer système, not necessary with update link and could raise error with switch and instance container.
- fix container libpath fix when updating or switching.
- fix nomenclature switch with update in append mode (numeral switching ".001" > ".002").

## bug to fix
- With several instances loaded in link mod, some empty object with broken link could remain.

2023-01-19 18:17 UTC, Tilix4 requested changes
ça me parait bien ! Sauf une petite interrogation.
Par contre il faut éviter de mélanger les changements de mise en forme avec les changements fonctionnels car c'est hyper relou à lire. :)

2023-01-19 18:17 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +    representations = []
Pourquoi ajouter ces deux là si ils sont hérités de `Loader` ?

2023-01-19 18:17 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        """Can be implemented by a sub-class"""
S'il n'y a rien dans la fonction ça ne va pas fonctionner. Je suis même surpris que ça passe l'import...

2023-01-20 09:24 UTC, kaamaurice commented on openpype/hosts/blender/api/plugin.py
> +    representations = []
Ah, oui c'est un oubli de ma part.

2023-01-20 09:27 UTC, kaamaurice commented on openpype/hosts/blender/api/plugin.py
> +        """Can be implemented by a sub-class"""
Oui j'ai trouvé ça étrange, j'avais un warning de mon linter:
Unnecessary pass statement Pylint(W0107:unnecessary-pass)

je vais laisser le pass je trouve ça plus safe.

2023-01-20 10:42 UTC, Tilix4 approved these changes
ça me parait bien !

2023-01-20 10:48 UTC, merged