Fix loader fbx and abc
kaamaurice/OpenPype pull request #44
Opened 2023-01-19 14:10 UTC by kaamaurice

## Brief description
Fix loader for fbx and abc representation.

## To do
- update and switch need to be fixed

2023-01-19 18:09 UTC, Tilix4 reviewed
Rien à dire sauf une petite question qui m'est venue à l'esprit !

2023-01-19 18:09 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        if not container_collection:
Ne devrait-on pas conditionner la colloction à plusieurs objets ? Si un seul objet alors l'importer tel quel.

2023-01-30 14:27 UTC, kaamaurice commented on openpype/hosts/blender/api/plugin.py
> +        if not container_collection:
Si on se libère de la collection pour définir un container OpenPype alors oui on peux imaginer importer sans collection un objet, ou même plusieurs objet, mais si on veux avoir deux comportement diffèrent alors optons pout deux loaders : `import as collection` / `import as objects set`

2023-02-28 09:44 UTC, Tilix4 requested changes
Nice refactor! Few changes still, but we are getting very close to something polished I'd say.

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +    """A basic AssetLoader for Blender.
In this case I think it must be called `BlenderLoader` if dedicated to load from Blender files.

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
>          container_name: str,
`container_name` given value is never used but always replaced by `outliner_entity.name`. It is the expected behaviour IMO, therefore remove this argument.

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        objects: List[bpy.types.Object],
It is not only objects but could be `collections` too. Stick to `outliner_entities` naming.

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +        datablocks = set(objects)
`outliner_entities` must be a set when provided to the function and not being cast.

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
>  class Loader(LoaderPlugin):
This class is useless, I think `AssetLoader` (renamed `BlenderLoader`) could be the one inheriting from `LoaderPlugin`

2023-02-28 09:44 UTC, Tilix4 commented on openpype/hosts/blender/api/plugin.py
> +    def _instance_blend(
Because we are refactoring, this one could be moved right after the `_link_blend`.

2025-01-23 08:38 UTC, closed without merging