Fix recursive filtering for Loader
kaamaurice/OpenPype pull request #79
Opened 2023-03-07 10:29 UTC by kaamaurice

## Brief description
Since OP 3.15.0 Loader doesn't filter asset list recursively

2023-03-07 10:36 UTC, Sharkitty approved these changes
LGTM

2023-03-07 12:24 UTC, Tilix4 commented
Isn't it something that must go into OP's core code?

2023-03-09 09:48 UTC, Tilix4 requested changes

2023-03-09 09:48 UTC, Tilix4 commented on openpype/tools/utils/models.py
> +    def __init__(self, *args, **kwargs):
`__init__` must be as close to the class name as possible.

2023-03-09 10:16 UTC, Tilix4 commented
Created PR to `develop`: https://github.com/ynput/OpenPype/pull/4595

2023-03-15 09:18 UTC, closed without merging